# Generated by Django 5.2.8 on 2025-11-21 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Марка автомобиля')),
                ('description', models.TextField(blank=True, verbose_name='Описание марки')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
            },
        ),
        migrations.CreateModel(
            name='RepairCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория работ')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория работ',
                'verbose_name_plural': 'Категории работ',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('production_years', models.CharField(blank=True, max_length=50, verbose_name='Годы выпуска')),
                ('engine_options', models.TextField(blank=True, verbose_name='Двигатели')),
                ('notes', models.TextField(blank=True, verbose_name='Особенности')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kladez_app.carbrand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
            },
        ),
        migrations.CreateModel(
            name='RepairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Вид работ')),
                ('description', models.TextField(blank=True, verbose_name='Описание работ')),
                ('typical_duration', models.CharField(blank=True, max_length=50, verbose_name='Типовая длительность')),
                ('complexity', models.CharField(blank=True, max_length=50, verbose_name='Сложность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kladez_app.repaircategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вид работ',
                'verbose_name_plural': 'Виды работ',
            },
        ),
        migrations.CreateModel(
            name='CompletedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выполнения')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость работы')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('parts_used', models.TextField(blank=True, verbose_name='Использованные запчасти')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kladez_app.carbrand', verbose_name='Марка')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kladez_app.carmodel', verbose_name='Модель')),
                ('repair_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kladez_app.repairtype', verbose_name='Вид работ')),
            ],
            options={
                'verbose_name': 'Выполненная работа',
                'verbose_name_plural': 'Выполненные работы',
                'ordering': ['-work_date'],
            },
        ),
    ]
