# Generated by Django 5.2.8 on 2025-12-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kladez_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedwork',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
